### ISSUE TITLE
Mapping

### ISSUE THREAD

**Issue by guicalman** [BioSchemas/Templates#10]
Before make the contrast between all de Use Cases, select the Schema.org Type that best fits all the use cases, after this process you would have to follow the process bellow to map the Schema.org properties to the Use Case's need.

- [x] Create a Mapping Template #6 
- [x] Mapping Feedback #7 
- [x] Publish Mapping template in Google Docs #8 
- [ ]  Document process to handle Mapping Template #9
