### ISSUE TITLE
Specification

### ISSUE THREAD

**Issue by guicalman** [BioSchemas/Templates#11]
After doing the mapping Bioschemas Specification should be done, to accomplish this goal we will follow the steps below:
- [x] Create a Specification Template in Google Docs
- [x] Convert the GDocs Template to a Markdown template
-  [x] Share some examples to comunity for feedback
- [ ] Integrate Jekyll based Bioschemas Web Page (local) with new section that list the Specifications and show the in Bioschemas page
- [ ] Publish MD Specification Template
- [ ] Document process to convert GDocs file into MD Specification file
