### ISSUE TITLE
Use Case

### ISSUE THREAD

**Issue by guicalman** [BioSchemas/Templates#5]
Generate the Use Case Template in Google Docs Format.
This issue is divided in the following tasks:
- [ ] Check the Use Case Files done in previous meetings #2 
- [ ] Propose new Use Case Template #3 
- [ ] Document the Use Case Template in Github #4
